### ISSUE TITLE
Problem to install binaries (not found)

### ISSUE THREAD

**Issue by Lualobus** [strands-project-releases/strands-releases#1]
curl -s http://lcas.lincoln.ac.uk/repos/public.key | sudo apt-key add -

sudo apt-add-repository http://lcas.lincoln.ac.uk/repos/building

sudo apt-get update

sudo apt-get install ros-hydro-strands-robot
   Reading package lists... Done
   Building dependency tree  
   Reading state information... Done
   E: Unable to locate package ros-hydro-strands-robot

**Comment by hawesie** [comment]
I think this is because we've turned off support for hydro, and now the build farm only supports indigo. Sorry about this. You can see the list of available packages here: https://lcas.lincoln.ac.uk/jenkins/job/repositories_report/lastSuccessfulBuild/artifact/repo.html

**Comment by marc-hanheide** [comment]
yes, we have ceased support for hydro in January, I'm afraid. Our limited build farm cannot maintain packages for different releases. I suggest you update to indigo if this is an option for you.

**Comment by Lualobus** [comment]
I am not possible to download de indigo ros versions of strands.

Are you sure that all is okey?

Best!

2015-06-03 17:10 GMT+02:00 Marc Hanheide notifications@github.com:

> yes, we have ceased support for hydro in January, I'm afraid. Our limited
> build farm cannot maintain packages for different releases. I suggest you
> update to indigo if this is an option for you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strands-project-releases/strands-releases/issues/1#issuecomment-108477529
> .

## 

Fernando Alonso Martín
Lualobus@gmail.com
http://roboticnaturalinteraction.com
http://www.roboticNaturalInteraction.com/famartin.html

**Comment by cdondrup** [comment]
Can you post your system specifications?
Operating system should ideally be Ubuntu 14.04 64-bit and of course the installed ROS version has to be indigo.

**Comment by Lualobus** [comment]
My Ubuntu is 12.04 32 bits. But the packages are not found in apt-get.

Best!

2015-06-10 17:33 GMT+02:00 Christian Dondrup notifications@github.com:

> Can you post your system specifications?
> Operating system should ideally be Ubuntu 14.04 64-bit and of course the
> installed ROS version has to be indigo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strands-project-releases/strands-releases/issues/1#issuecomment-110798447
> .

## 

Fernando Alonso Martín
Lualobus@gmail.com
http://roboticnaturalinteraction.com
http://www.roboticNaturalInteraction.com/famartin.html

**Comment by marc-hanheide** [comment]
Sorry, we only provide packages for 14.04 64 bit at the moment. Could you update? You can also compile from source.

**Comment by hawesie** [comment]
The source install should work for 12.04 32 bits. You can generate an install manifest using

``` bash
ROSDISTRO_INDEX_URL=https://raw.github.com/strands-project/rosdistro/strands-devel/index.yaml rosinstall_generator strands_robot --rosdistro indigo --wet-only --deps > strands_robot.rosinstall
```

Then use this as you would in a [source install](http://wiki.ros.org/indigo/Installation/Source)/

**Comment by marc-hanheide** [comment]
I assume this is resolved. If not, please re-open.
