### ISSUE TITLE
v4r package for ROS Indingo is not found

### ISSUE THREAD

**Issue by vovaekb** [strands-project-releases/strands-releases#2]
Hi!
I have laptop with Ubuntu 14.04 64bit and ROS Indigo. I have complete all the steps from the wiki: https://github.com/strands-project-releases/strands-releases/wiki#using-the-strands-repository. But the system can't find the package ros-indigo-v4r.

**Comment by marc-hanheide** [comment]
Could you try the following steps, please:
1. `sudo apt-get update` and watch out for lines that contains "lcas.lincoln.ac.uk", and paste them as comment to this issue
2. run `sudo apt-get install ros-indigo-v4r` and paste the output of this commant as well.

**Comment by vovaekb** [comment]
1. Output from sudo apt-get update:
   Hit http://lcas.lincoln.ac.uk trusty InRelease 
   ...
   Hit http://lcas.lincoln.ac.uk trusty/main i386 Packages
   Ign http://lcas.lincoln.ac.uk trusty/main Translation-en_US
   Ign http://lcas.lincoln.ac.uk trusty/main Translation-en
2. Output from sudo apt-get install ros-indigo-v4r:
   Reading package lists... Done
   Building dependency tree  
   Reading state information... Done
   E: Unable to locate package ros-indigo-v4r

**Comment by marc-hanheide** [comment]
looks as if you've got 32 not 64 bit installed:
'Hit http://lcas.lincoln.ac.uk trusty/main i386 Packages'

**Comment by vovaekb** [comment]
I was mistaken. I have 32 bit

**Comment by marc-hanheide** [comment]
I'm afraid, we don't provide binaries for 32bit at the moment. If you can, reinstall 64bit, or look at #1 for some ideas about installing from source.

**Comment by vovaekb** [comment]
OK. Thank you for help! I will solve it in some way.
