### ISSUE TITLE
Error at the "Database Launch" step in the Example STRANDS System Page

### ISSUE THREAD

**Issue by FcoMelendez** [strands-project-releases/strands-releases#4]
Hello!
I'm trying to test the examples available at the "Example STRANDS System Page". I get the following error:

CMD:
roslaunch mongodb_store mongodb_store.launch db_path:='path to my db_dir'/strands_sim_example

ERROR:
_Traceback (most recent call last):
  File "/opt/ros/indigo/lib/mongodb_store/message_store_node.py", line 21, in <module>
    class MessageStore(object):
  File "/opt/ros/indigo/lib/mongodb_store/message_store_node.py", line 321, in MessageStore
    query_with_projection_messages_ros_srv.type=dc_srv.MongoQuerywithProjectionMsg
AttributeError: 'module' object has no attribute 'MongoQuerywithProjectionMsg'_

**Comment by hawesie** [comment]
Thanks for trying our code!
This is a known current issue: https://github.com/strands-project/mongodb_store/issues/182
If you install mongodb_store from source it goes away, but we're still looking for a proper fix.

**Comment by FcoMelendez** [comment]
Working!
Thanks for your prompt and helpful answer : )
